# Form implementation generated from reading ui file 'd:\Python\Bai tap\LapTrinhHDT\GUI\complete12 - Copy.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1079)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 1921, 1081))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(218, 187, 221, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(1150, 60, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 20px;\n"
"border: 5px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(880, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(-1, -1, 771, 1081))
        self.widget_2.setStyleSheet("border-top-right-radius: 80px;\n"
"border-bottom-right-radius: 80px;\n"
"border-image: url(:/com12/z3939808018009-254199a3526d0d8fbd4bd13164718550-53.jpg);")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(1000, 210, 641, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.ans_p2_12_1 = QtWidgets.QLineEdit(parent=self.widget)
        self.ans_p2_12_1.setGeometry(QtCore.QRect(1000, 310, 641, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ans_p2_12_1.setFont(font)
        self.ans_p2_12_1.setStyleSheet("QLineEdit {\n"
"border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid white;\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid red;\n"
"}")
        self.ans_p2_12_1.setObjectName("ans_p2_12_1")
        self.check_p2_12_1 = QtWidgets.QPushButton(parent=self.widget)
        self.check_p2_12_1.setGeometry(QtCore.QRect(1670, 320, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_p2_12_1.setFont(font)
        self.check_p2_12_1.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check_p2_12_1.setObjectName("check_p2_12_1")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(880, 450, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(990, 450, 691, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.ans_p2_12_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.ans_p2_12_2.setGeometry(QtCore.QRect(990, 550, 691, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ans_p2_12_2.setFont(font)
        self.ans_p2_12_2.setStyleSheet("QLineEdit {\n"
"border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid white;\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid red;\n"
"}")
        self.ans_p2_12_2.setObjectName("ans_p2_12_2")
        self.check_p2_12_2 = QtWidgets.QPushButton(parent=self.widget)
        self.check_p2_12_2.setGeometry(QtCore.QRect(1710, 560, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_p2_12_2.setFont(font)
        self.check_p2_12_2.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check_p2_12_2.setObjectName("check_p2_12_2")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(880, 710, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setGeometry(QtCore.QRect(990, 700, 711, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.ans_p2_12_3 = QtWidgets.QLineEdit(parent=self.widget)
        self.ans_p2_12_3.setGeometry(QtCore.QRect(990, 800, 711, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ans_p2_12_3.setFont(font)
        self.ans_p2_12_3.setStyleSheet("QLineEdit {\n"
"border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid white;\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid red;\n"
"}")
        self.ans_p2_12_3.setObjectName("ans_p2_12_3")
        self.check_p2_12_3 = QtWidgets.QPushButton(parent=self.widget)
        self.check_p2_12_3.setGeometry(QtCore.QRect(1730, 810, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_p2_12_3.setFont(font)
        self.check_p2_12_3.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check_p2_12_3.setObjectName("check_p2_12_3")
        self.back_ex12 = QtWidgets.QPushButton(parent=self.widget)
        self.back_ex12.setGeometry(QtCore.QRect(800, 930, 93, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.back_ex12.setFont(font)
        self.back_ex12.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.back_ex12.setObjectName("back_ex12")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Question 2. Complete the sentences:"))
        self.label_2.setText(_translate("MainWindow", "1."))
        self.label_3.setText(_translate("MainWindow", "にほんの / あした / ありますよ。 / えいがが"))
        self.check_p2_12_1.setText(_translate("MainWindow", "Check"))
        self.label_4.setText(_translate("MainWindow", "2."))
        self.label_5.setText(_translate("MainWindow", "コンサートが / ありますよ。 / らいげつ / たいこの"))
        self.check_p2_12_2.setText(_translate("MainWindow", "Check"))
        self.label_6.setText(_translate("MainWindow", "3."))
        self.label_7.setText(_translate("MainWindow", "ＪＦスポーツセンター /  なにが ありますか。 / で"))
        self.check_p2_12_3.setText(_translate("MainWindow", "Check"))
        self.back_ex12.setText(_translate("MainWindow", "Back"))
