# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'complete14.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1079)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 1921, 1081))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 159, 144, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(1150, 60, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 20px;\n"
"border: 5px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(880, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(-1, -1, 771, 1081))
        self.widget_2.setStyleSheet("border-top-right-radius: 80px;\n"
"border-bottom-right-radius: 80px;\n"
"border-image: url(:/com14/hoa-anh-dao-Tokyo-Skytree-496x620.jpg);")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(1000, 210, 641, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.ans_p2_14_1 = QtWidgets.QLineEdit(self.widget)
        self.ans_p2_14_1.setGeometry(QtCore.QRect(1000, 310, 641, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ans_p2_14_1.setFont(font)
        self.ans_p2_14_1.setStyleSheet("QLineEdit {\n"
"border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid white;\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid red;\n"
"}")
        self.ans_p2_14_1.setObjectName("ans_p2_14_1")
        self.check_p2_14_1 = QtWidgets.QPushButton(self.widget)
        self.check_p2_14_1.setGeometry(QtCore.QRect(1670, 320, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_p2_14_1.setFont(font)
        self.check_p2_14_1.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check_p2_14_1.setObjectName("check_p2_14_1")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(880, 450, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(990, 450, 691, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.ans_p2_14_2 = QtWidgets.QLineEdit(self.widget)
        self.ans_p2_14_2.setGeometry(QtCore.QRect(990, 550, 691, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ans_p2_14_2.setFont(font)
        self.ans_p2_14_2.setStyleSheet("QLineEdit {\n"
"border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid white;\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid red;\n"
"}")
        self.ans_p2_14_2.setObjectName("ans_p2_14_2")
        self.check_p2_14_2 = QtWidgets.QPushButton(self.widget)
        self.check_p2_14_2.setGeometry(QtCore.QRect(1710, 560, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_p2_14_2.setFont(font)
        self.check_p2_14_2.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check_p2_14_2.setObjectName("check_p2_14_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(880, 710, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(990, 710, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.ans_p2_14_3 = QtWidgets.QLineEdit(self.widget)
        self.ans_p2_14_3.setGeometry(QtCore.QRect(990, 800, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ans_p2_14_3.setFont(font)
        self.ans_p2_14_3.setStyleSheet("QLineEdit {\n"
"border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid white;\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid red;\n"
"}")
        self.ans_p2_14_3.setObjectName("ans_p2_14_3")
        self.check_p2_14_3 = QtWidgets.QPushButton(self.widget)
        self.check_p2_14_3.setGeometry(QtCore.QRect(1730, 810, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_p2_14_3.setFont(font)
        self.check_p2_14_3.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check_p2_14_3.setObjectName("check_p2_14_3")
        self.back_ex14 = QtWidgets.QPushButton(self.widget)
        self.back_ex14.setGeometry(QtCore.QRect(800, 930, 93, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.back_ex14.setFont(font)
        self.back_ex14.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.back_ex14.setObjectName("back_ex14")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.check_p2_14_1.clicked.connect(self.check_answerp2_14_1)
        self.check_p2_14_2.clicked.connect(self.check_answerp2_14_2)
        self.check_p2_14_3.clicked.connect(self.check_answerp2_14_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Question 2. Complete the sentences:"))
        self.label_2.setText(_translate("MainWindow", "1."))
        self.label_3.setText(_translate("MainWindow", "あります。 / おてらが / 古い / きょうとに"))
        self.check_p2_14_1.setText(_translate("MainWindow", "Check"))
        self.label_4.setText(_translate("MainWindow", "2."))
        self.label_5.setText(_translate("MainWindow", "わたしの / まちに / にぎやかな / あります。 / こうえんが"))
        self.check_p2_14_2.setText(_translate("MainWindow", "Check"))
        self.label_6.setText(_translate("MainWindow", "3."))
        self.label_7.setText(_translate("MainWindow", "レストランが / あります。 / まえに / おいしい / こうえんの\n"
""))
        self.check_p2_14_3.setText(_translate("MainWindow", "Check"))
        self.back_ex14.setText(_translate("MainWindow", "Back"))

    def check_answerp2_14_1(self):
        selected_answerp2_14_1 = self.ans_p2_14_1.text()
        if selected_answerp2_14_1 == 'きょうとに　古い　おてらが　あります。':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()
    def check_answerp2_14_2(self):
        selected_answerp2_14_2 = self.ans_p2_14_2.text()
        if selected_answerp2_14_2 == 'わたしの　まちに　にぎやかな　こうえんが　あります。':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()

    def check_answerp2_14_3(self):
        selected_answerp2_14_3 = self.ans_p2_14_3.text()
        if selected_answerp2_14_3 == 'こうえんの　まえに　おいしい　レストランが　あります。':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()

import com14_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
