# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercises13.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1969, 1060)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 1971, 1061))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 961, 1061))
        self.widget_2.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(189, 182, 120, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(60, 200, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(60, 490, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.q2 = QtWidgets.QLabel(self.widget_2)
        self.q2.setGeometry(QtCore.QRect(160, 460, 751, 151))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2.setFont(font)
        self.q2.setMouseTracking(False)
        self.q2.setTabletTracking(False)
        self.q2.setAcceptDrops(False)
        self.q2.setAutoFillBackground(False)
        self.q2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2.setScaledContents(False)
        self.q2.setWordWrap(True)
        self.q2.setObjectName("q2")
        self.ans13_2_1 = QtWidgets.QComboBox(self.widget_2)
        self.ans13_2_1.setGeometry(QtCore.QRect(260, 490, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_2_1.setFont(font)
        self.ans13_2_1.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_2_1.setObjectName("ans13_2_1")
        self.ans13_2_1.addItem("")
        self.ans13_2_1.addItem("")
        self.ans13_2_1.addItem("")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(60, 720, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.check13_1 = QtWidgets.QPushButton(self.widget_2)
        self.check13_1.setGeometry(QtCore.QRect(410, 360, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_1.setFont(font)
        self.check13_1.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_1.setObjectName("check13_1")
        self.check13_2 = QtWidgets.QPushButton(self.widget_2)
        self.check13_2.setGeometry(QtCore.QRect(410, 630, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_2.setFont(font)
        self.check13_2.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_2.setObjectName("check13_2")
        self.q2_2 = QtWidgets.QLabel(self.widget_2)
        self.q2_2.setGeometry(QtCore.QRect(160, 700, 701, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2_2.setFont(font)
        self.q2_2.setMouseTracking(False)
        self.q2_2.setTabletTracking(False)
        self.q2_2.setAcceptDrops(False)
        self.q2_2.setAutoFillBackground(False)
        self.q2_2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2_2.setScaledContents(False)
        self.q2_2.setObjectName("q2_2")
        self.check13_3 = QtWidgets.QPushButton(self.widget_2)
        self.check13_3.setGeometry(QtCore.QRect(400, 840, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_3.setFont(font)
        self.check13_3.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_3.setObjectName("check13_3")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(250, 30, 451, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 20px;\n"
"border: 2px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.back_gr13 = QtWidgets.QPushButton(self.widget_2)
        self.back_gr13.setGeometry(QtCore.QRect(30, 920, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.back_gr13.setFont(font)
        self.back_gr13.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.back_gr13.setObjectName("back_gr13")
        self.q1_3 = QtWidgets.QLabel(self.widget_2)
        self.q1_3.setGeometry(QtCore.QRect(140, 130, 731, 201))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.q1_3.setFont(font)
        self.q1_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.q1_3.setMouseTracking(True)
        self.q1_3.setTabletTracking(False)
        self.q1_3.setAcceptDrops(False)
        self.q1_3.setAutoFillBackground(False)
        self.q1_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.q1_3.setScaledContents(False)
        self.q1_3.setWordWrap(True)
        self.q1_3.setIndent(10)
        self.q1_3.setOpenExternalLinks(False)
        self.q1_3.setObjectName("q1_3")
        self.ans13_1_2 = QtWidgets.QComboBox(self.widget_2)
        self.ans13_1_2.setGeometry(QtCore.QRect(590, 150, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_1_2.setFont(font)
        self.ans13_1_2.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_1_2.setObjectName("ans13_1_2")
        self.ans13_1_2.addItem("")
        self.ans13_1_2.addItem("")
        self.ans13_1_2.addItem("")
        self.ans13_1_1 = QtWidgets.QComboBox(self.widget_2)
        self.ans13_1_1.setGeometry(QtCore.QRect(310, 150, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_1_1.setFont(font)
        self.ans13_1_1.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_1_1.setObjectName("ans13_1_1")
        self.ans13_1_1.addItem("")
        self.ans13_1_1.addItem("")
        self.ans13_1_1.addItem("")
        self.ans13_1_3 = QtWidgets.QComboBox(self.widget_2)
        self.ans13_1_3.setGeometry(QtCore.QRect(420, 260, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_1_3.setFont(font)
        self.ans13_1_3.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_1_3.setObjectName("ans13_1_3")
        self.ans13_1_3.addItem("")
        self.ans13_1_3.addItem("")
        self.ans13_1_3.addItem("")
        self.ans13_2_2 = QtWidgets.QComboBox(self.widget_2)
        self.ans13_2_2.setGeometry(QtCore.QRect(510, 490, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_2_2.setFont(font)
        self.ans13_2_2.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_2_2.setObjectName("ans13_2_2")
        self.ans13_2_2.addItem("")
        self.ans13_2_2.addItem("")
        self.ans13_2_2.addItem("")
        self.ans13_2_3 = QtWidgets.QComboBox(self.widget_2)
        self.ans13_2_3.setGeometry(QtCore.QRect(780, 490, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_2_3.setFont(font)
        self.ans13_2_3.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_2_3.setObjectName("ans13_2_3")
        self.ans13_2_3.addItem("")
        self.ans13_2_3.addItem("")
        self.ans13_2_3.addItem("")
        self.ans13_3_1 = QtWidgets.QComboBox(self.widget_2)
        self.ans13_3_1.setGeometry(QtCore.QRect(330, 730, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_3_1.setFont(font)
        self.ans13_3_1.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_3_1.setObjectName("ans13_3_1")
        self.ans13_3_1.addItem("")
        self.ans13_3_1.addItem("")
        self.ans13_3_1.addItem("")
        self.ans13_3_2 = QtWidgets.QComboBox(self.widget_2)
        self.ans13_3_2.setGeometry(QtCore.QRect(590, 730, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_3_2.setFont(font)
        self.ans13_3_2.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_3_2.setObjectName("ans13_3_2")
        self.ans13_3_2.addItem("")
        self.ans13_3_2.addItem("")
        self.ans13_3_2.addItem("")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(960, 0, 1001, 1061))
        self.widget_3.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(189, 182, 120, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:0, y2:1, stop:0 rgba(189, 182, 120, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget_3.setObjectName("widget_3")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(70, 100, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.q1_2 = QtWidgets.QLabel(self.widget_3)
        self.q1_2.setGeometry(QtCore.QRect(160, 70, 711, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.q1_2.setFont(font)
        self.q1_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.q1_2.setMouseTracking(True)
        self.q1_2.setTabletTracking(False)
        self.q1_2.setAcceptDrops(False)
        self.q1_2.setAutoFillBackground(False)
        self.q1_2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.q1_2.setScaledContents(False)
        self.q1_2.setWordWrap(True)
        self.q1_2.setObjectName("q1_2")
        self.ans13_4_1 = QtWidgets.QComboBox(self.widget_3)
        self.ans13_4_1.setGeometry(QtCore.QRect(330, 100, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_4_1.setFont(font)
        self.ans13_4_1.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_4_1.setObjectName("ans13_4_1")
        self.ans13_4_1.addItem("")
        self.ans13_4_1.addItem("")
        self.ans13_4_1.addItem("")
        self.ans13_4_2 = QtWidgets.QComboBox(self.widget_3)
        self.ans13_4_2.setGeometry(QtCore.QRect(550, 100, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_4_2.setFont(font)
        self.ans13_4_2.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_4_2.setObjectName("ans13_4_2")
        self.ans13_4_2.addItem("")
        self.ans13_4_2.addItem("")
        self.ans13_4_2.addItem("")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(60, 430, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.check13_4 = QtWidgets.QPushButton(self.widget_3)
        self.check13_4.setGeometry(QtCore.QRect(430, 240, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_4.setFont(font)
        self.check13_4.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_4.setObjectName("check13_4")
        self.check13_5 = QtWidgets.QPushButton(self.widget_3)
        self.check13_5.setGeometry(QtCore.QRect(410, 570, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_5.setFont(font)
        self.check13_5.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_5.setObjectName("check13_5")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(50, 740, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.q2_3 = QtWidgets.QLabel(self.widget_3)
        self.q2_3.setGeometry(QtCore.QRect(150, 720, 641, 121))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2_3.setFont(font)
        self.q2_3.setMouseTracking(False)
        self.q2_3.setTabletTracking(False)
        self.q2_3.setAcceptDrops(False)
        self.q2_3.setAutoFillBackground(False)
        self.q2_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2_3.setScaledContents(False)
        self.q2_3.setWordWrap(True)
        self.q2_3.setObjectName("q2_3")
        self.ans13_6 = QtWidgets.QComboBox(self.widget_3)
        self.ans13_6.setGeometry(QtCore.QRect(550, 760, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_6.setFont(font)
        self.ans13_6.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_6.setObjectName("ans13_6")
        self.ans13_6.addItem("")
        self.ans13_6.addItem("")
        self.ans13_6.addItem("")
        self.check13_6 = QtWidgets.QPushButton(self.widget_3)
        self.check13_6.setGeometry(QtCore.QRect(410, 870, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check13_6.setFont(font)
        self.check13_6.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check13_6.setObjectName("check13_6")
        self.q1 = QtWidgets.QLabel(self.widget_3)
        self.q1.setGeometry(QtCore.QRect(210, 410, 621, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q1.setFont(font)
        self.q1.setMouseTracking(False)
        self.q1.setTabletTracking(False)
        self.q1.setAcceptDrops(False)
        self.q1.setAutoFillBackground(False)
        self.q1.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1.setScaledContents(False)
        self.q1.setObjectName("q1")
        self.ans13_5 = QtWidgets.QComboBox(self.widget_3)
        self.ans13_5.setGeometry(QtCore.QRect(590, 440, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ans13_5.setFont(font)
        self.ans13_5.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans13_5.setObjectName("ans13_5")
        self.ans13_5.addItem("")
        self.ans13_5.addItem("")
        self.ans13_5.addItem("")
        self.nextp2_13 = QtWidgets.QPushButton(self.widget_3)
        self.nextp2_13.setGeometry(QtCore.QRect(790, 910, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nextp2_13.setFont(font)
        self.nextp2_13.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.nextp2_13.setObjectName("nextp2_13")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.check13_1.clicked.connect(self.check_answer13_1)
        self.check13_2.clicked.connect(self.check_answer13_2)
        self.check13_3.clicked.connect(self.check_answer13_3)
        self.check13_4.clicked.connect(self.check_answer13_4)
        self.check13_5.clicked.connect(self.check_answer13_5)
        self.check13_6.clicked.connect(self.check_answer13_6)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "2"))
        self.q2.setText(_translate("MainWindow", "うち         がっこう　　　　でんしゃ　　　　　いきます。"))
        self.ans13_2_1.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_2_1.setItemText(1, _translate("MainWindow", "から"))
        self.ans13_2_1.setItemText(2, _translate("MainWindow", "まで"))
        self.label_5.setText(_translate("MainWindow", "3"))
        self.check13_1.setText(_translate("MainWindow", "Check"))
        self.check13_2.setText(_translate("MainWindow", "Check"))
        self.q2_2.setText(_translate("MainWindow", "ホテル           タクシー         おります。"))
        self.check13_3.setText(_translate("MainWindow", "Check"))
        self.label.setText(_translate("MainWindow", "Question 1. Choose the correct word:"))
        self.back_gr13.setText(_translate("MainWindow", "Back"))
        self.q1_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.q1_3.setText(_translate("MainWindow", "Ａ：どこ           ちかてつ            のりますか。                                          B: さくらえき              のります。"))
        self.ans13_1_2.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_1_2.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_1_2.setItemText(2, _translate("MainWindow", "で"))
        self.ans13_1_1.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_1_1.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_1_1.setItemText(2, _translate("MainWindow", "で"))
        self.ans13_1_3.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_1_3.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_1_3.setItemText(2, _translate("MainWindow", "で"))
        self.ans13_2_2.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_2_2.setItemText(1, _translate("MainWindow", "から"))
        self.ans13_2_2.setItemText(2, _translate("MainWindow", "まで"))
        self.ans13_2_3.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_2_3.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_2_3.setItemText(2, _translate("MainWindow", "で"))
        self.ans13_3_1.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_3_1.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_3_1.setItemText(2, _translate("MainWindow", "で"))
        self.ans13_3_2.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_3_2.setItemText(1, _translate("MainWindow", "に"))
        self.ans13_3_2.setItemText(2, _translate("MainWindow", "を"))
        self.label_6.setText(_translate("MainWindow", "4"))
        self.q1_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; color:#717171; background-color:#fffdf7;\">テーブルの うえ           バナナ</span><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; font-weight:400; color:#717171; background-color:#fffdf7;\"/><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; color:#717171; background-color:#fffdf7;\">あります。</span></p><p><br/><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; color:#717171;\"/><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; font-weight:400; color:#717171;\"/><a name=\"ui-id-4-button\"/><a href=\"https://a1.marugotoweb.jp/en/grammar_topic6_11.php#nogo\"><span style=\" font-family:\'Verdana\',\'Arial\',\'sans-serif\'; font-size:20px; font-weight:400; color:#666666; background-color:#fffdf7; vertical-align:middle;\"><br/></span></a><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; font-weight:400; color:#717171;\"/><a name=\"ui-id-4-button\"/><a href=\"https://a1.marugotoweb.jp/en/grammar_topic6_11.php#nogo\"><span style=\" font-family:\'Verdana\',\'Arial\',\'sans-serif\'; font-size:20px; font-weight:400; color:#666666; background-color:#fffdf7; vertical-align:middle;\"><br/></span></a></p></body></html>"))
        self.q1_2.setText(_translate("MainWindow", "くうこう            バス         　いいです。"))
        self.ans13_4_1.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_4_1.setItemText(1, _translate("MainWindow", "は"))
        self.ans13_4_1.setItemText(2, _translate("MainWindow", "が"))
        self.ans13_4_2.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_4_2.setItemText(1, _translate("MainWindow", "は"))
        self.ans13_4_2.setItemText(2, _translate("MainWindow", "が"))
        self.label_7.setText(_translate("MainWindow", "5"))
        self.check13_4.setText(_translate("MainWindow", "Check"))
        self.check13_5.setText(_translate("MainWindow", "Check"))
        self.label_8.setText(_translate("MainWindow", "6"))
        self.q2_3.setText(_translate("MainWindow", "がっこうまで　あるいて　　　　　　。"))
        self.ans13_6.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_6.setItemText(1, _translate("MainWindow", "いきます"))
        self.ans13_6.setItemText(2, _translate("MainWindow", "おります"))
        self.check13_6.setText(_translate("MainWindow", "Check"))
        self.q1.setText(_translate("MainWindow", "くうこうで　ひこうきに　　　　　　　。"))
        self.ans13_5.setItemText(0, _translate("MainWindow", "?"))
        self.ans13_5.setItemText(1, _translate("MainWindow", "のります"))
        self.ans13_5.setItemText(2, _translate("MainWindow", "おります"))
        self.nextp2_13.setText(_translate("MainWindow", "Next"))

    def check_answer13_1(self):
        selected_answer13_1_1 = self.ans13_1_1.currentText()
        selected_answer13_1_2 = self.ans13_1_2.currentText()
        selected_answer13_1_3 = self.ans13_1_3.currentText()
        if selected_answer13_1_1 == 'で' and selected_answer13_1_2 == 'に' and selected_answer13_1_3 == 'で':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()
    def check_answer13_2(self):
        selected_answer13_2_1 = self.ans13_2_1.currentText()
        selected_answer13_2_2 = self.ans13_2_2.currentText()
        selected_answer13_2_3 = self.ans13_2_3.currentText()
        if selected_answer13_2_1 == 'から' and selected_answer13_2_2 == 'まで' and selected_answer13_2_3 == 'で':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()

    def check_answer13_3(self):
        selected_answer13_3_1 = self.ans13_3_1.currentText()
        selected_answer13_3_2 = self.ans13_3_2.currentText()
        if selected_answer13_3_1 == 'で' and selected_answer13_3_2 == 'を':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()
    def check_answer13_4(self):
        selected_answer13_4_1 = self.ans13_4_1.currentText()
        selected_answer13_4_2 = self.ans13_4_2.currentText()
        if selected_answer13_4_1 == 'は' and selected_answer13_4_2 =='が':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()
    def check_answer13_5(self):
        selected_answer13_5 = self.ans13_5.currentText()
        if selected_answer13_5 == 'のります':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()
    def check_answer13_6(self):
        selected_answer13_6 = self.ans13_6.currentText()
        if selected_answer13_6 == 'いきます':
                msg = QMessageBox()
                msg.setText("You are Correct!!!")
                msg.exec_()
        else:
                msg = QMessageBox()
                msg.setText("Incorrect!!! Try again.")
                msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
