# Form implementation generated from reading ui file 'd:\Python\Bai tap\LapTrinhHDT\GUI\exercises.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 1008)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1911, 1011))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 961, 1011))
        self.widget_2.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(189, 182, 120, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget_2.setObjectName("widget_2")
        self.q1 = QtWidgets.QLabel(parent=self.widget_2)
        self.q1.setGeometry(QtCore.QRect(200, 180, 591, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q1.setFont(font)
        self.q1.setMouseTracking(False)
        self.q1.setTabletTracking(False)
        self.q1.setAcceptDrops(False)
        self.q1.setAutoFillBackground(False)
        self.q1.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1.setScaledContents(False)
        self.q1.setObjectName("q1")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(60, 200, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.ans11_1 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans11_1.setGeometry(QtCore.QRect(360, 210, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_1.setFont(font)
        self.ans11_1.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_1.setObjectName("ans11_1")
        self.ans11_1.addItem("")
        self.ans11_1.addItem("")
        self.ans11_1.addItem("")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(60, 450, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.q2 = QtWidgets.QLabel(parent=self.widget_2)
        self.q2.setGeometry(QtCore.QRect(160, 430, 661, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2.setFont(font)
        self.q2.setMouseTracking(False)
        self.q2.setTabletTracking(False)
        self.q2.setAcceptDrops(False)
        self.q2.setAutoFillBackground(False)
        self.q2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2.setScaledContents(False)
        self.q2.setObjectName("q2")
        self.ans11_2 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans11_2.setGeometry(QtCore.QRect(340, 460, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_2.setFont(font)
        self.ans11_2.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_2.setObjectName("ans11_2")
        self.ans11_2.addItem("")
        self.ans11_2.addItem("")
        self.ans11_2.addItem("")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(60, 720, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.check11_1 = QtWidgets.QPushButton(parent=self.widget_2)
        self.check11_1.setGeometry(QtCore.QRect(400, 310, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_1.setFont(font)
        self.check11_1.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_1.setObjectName("check11_1")
        self.check11_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.check11_2.setGeometry(QtCore.QRect(400, 570, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_2.setFont(font)
        self.check11_2.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_2.setObjectName("check11_2")
        self.q2_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.q2_2.setGeometry(QtCore.QRect(160, 700, 661, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2_2.setFont(font)
        self.q2_2.setMouseTracking(False)
        self.q2_2.setTabletTracking(False)
        self.q2_2.setAcceptDrops(False)
        self.q2_2.setAutoFillBackground(False)
        self.q2_2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2_2.setScaledContents(False)
        self.q2_2.setObjectName("q2_2")
        self.ans11_3 = QtWidgets.QComboBox(parent=self.widget_2)
        self.ans11_3.setGeometry(QtCore.QRect(390, 730, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_3.setFont(font)
        self.ans11_3.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_3.setObjectName("ans11_3")
        self.ans11_3.addItem("")
        self.ans11_3.addItem("")
        self.ans11_3.addItem("")
        self.check11_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.check11_3.setGeometry(QtCore.QRect(400, 840, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_3.setFont(font)
        self.check11_3.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_3.setObjectName("check11_3")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setGeometry(QtCore.QRect(250, 30, 451, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 20px;\n"
"border: 2px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.back_gr11 = QtWidgets.QPushButton(parent=self.widget_2)
        self.back_gr11.setGeometry(QtCore.QRect(30, 920, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.back_gr11.setFont(font)
        self.back_gr11.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.back_gr11.setObjectName("back_gr11")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setGeometry(QtCore.QRect(960, 0, 941, 1011))
        self.widget_3.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(189, 182, 120, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:0, y2:1, stop:0 rgba(189, 182, 120, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget_3.setObjectName("widget_3")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(70, 100, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.q1_2 = QtWidgets.QLabel(parent=self.widget_3)
        self.q1_2.setGeometry(QtCore.QRect(160, 70, 711, 141))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.q1_2.setFont(font)
        self.q1_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.q1_2.setMouseTracking(True)
        self.q1_2.setTabletTracking(False)
        self.q1_2.setAcceptDrops(False)
        self.q1_2.setAutoFillBackground(False)
        self.q1_2.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.q1_2.setScaledContents(False)
        self.q1_2.setWordWrap(True)
        self.q1_2.setObjectName("q1_2")
        self.ans11_4_1 = QtWidgets.QComboBox(parent=self.widget_3)
        self.ans11_4_1.setGeometry(QtCore.QRect(480, 90, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_4_1.setFont(font)
        self.ans11_4_1.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_4_1.setObjectName("ans11_4_1")
        self.ans11_4_1.addItem("")
        self.ans11_4_1.addItem("")
        self.ans11_4_1.addItem("")
        self.ans11_4_2 = QtWidgets.QComboBox(parent=self.widget_3)
        self.ans11_4_2.setGeometry(QtCore.QRect(750, 90, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_4_2.setFont(font)
        self.ans11_4_2.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_4_2.setObjectName("ans11_4_2")
        self.ans11_4_2.addItem("")
        self.ans11_4_2.addItem("")
        self.ans11_4_2.addItem("")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(60, 430, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.check11_4 = QtWidgets.QPushButton(parent=self.widget_3)
        self.check11_4.setGeometry(QtCore.QRect(430, 250, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_4.setFont(font)
        self.check11_4.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_4.setObjectName("check11_4")
        self.q1_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.q1_3.setGeometry(QtCore.QRect(160, 400, 731, 181))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.q1_3.setFont(font)
        self.q1_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.q1_3.setMouseTracking(True)
        self.q1_3.setTabletTracking(False)
        self.q1_3.setAcceptDrops(False)
        self.q1_3.setAutoFillBackground(False)
        self.q1_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q1_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.q1_3.setScaledContents(False)
        self.q1_3.setWordWrap(True)
        self.q1_3.setIndent(10)
        self.q1_3.setOpenExternalLinks(False)
        self.q1_3.setObjectName("q1_3")
        self.ans11_5_1 = QtWidgets.QComboBox(parent=self.widget_3)
        self.ans11_5_1.setGeometry(QtCore.QRect(250, 430, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_5_1.setFont(font)
        self.ans11_5_1.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_5_1.setObjectName("ans11_5_1")
        self.ans11_5_1.addItem("")
        self.ans11_5_1.addItem("")
        self.ans11_5_1.addItem("")
        self.check11_5 = QtWidgets.QPushButton(parent=self.widget_3)
        self.check11_5.setGeometry(QtCore.QRect(440, 610, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_5.setFont(font)
        self.check11_5.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_5.setObjectName("check11_5")
        self.ans11_5_2 = QtWidgets.QComboBox(parent=self.widget_3)
        self.ans11_5_2.setGeometry(QtCore.QRect(390, 500, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_5_2.setFont(font)
        self.ans11_5_2.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_5_2.setObjectName("ans11_5_2")
        self.ans11_5_2.addItem("")
        self.ans11_5_2.addItem("")
        self.ans11_5_2.addItem("")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(50, 740, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.q2_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.q2_3.setGeometry(QtCore.QRect(150, 720, 711, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.q2_3.setFont(font)
        self.q2_3.setMouseTracking(False)
        self.q2_3.setTabletTracking(False)
        self.q2_3.setAcceptDrops(False)
        self.q2_3.setAutoFillBackground(False)
        self.q2_3.setStyleSheet("border-radius: 30px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.q2_3.setScaledContents(False)
        self.q2_3.setWordWrap(True)
        self.q2_3.setObjectName("q2_3")
        self.ans11_6 = QtWidgets.QComboBox(parent=self.widget_3)
        self.ans11_6.setGeometry(QtCore.QRect(460, 730, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ans11_6.setFont(font)
        self.ans11_6.setStyleSheet("border-top-left-radius: 20px;\n"
"border-bottom-left-radius:20px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.ans11_6.setObjectName("ans11_6")
        self.ans11_6.addItem("")
        self.ans11_6.addItem("")
        self.ans11_6.addItem("")
        self.check11_6 = QtWidgets.QPushButton(parent=self.widget_3)
        self.check11_6.setGeometry(QtCore.QRect(430, 860, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check11_6.setFont(font)
        self.check11_6.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.check11_6.setObjectName("check11_6")
        self.nextp2_11 = QtWidgets.QPushButton(parent=self.widget_3)
        self.nextp2_11.setGeometry(QtCore.QRect(800, 930, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nextp2_11.setFont(font)
        self.nextp2_11.setStyleSheet("QPushButton {\n"
"border-radius: 25px;\n"
"border: 2px solid black;\n"
"padding: 15px;\n"
"background-color:rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(170, 255, 255);\n"
"}")
        self.nextp2_11.setObjectName("nextp2_11")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.q1.setText(_translate("MainWindow", "えいご　　　　　　　できます。"))
        self.label_3.setText(_translate("MainWindow", "1"))
        self.ans11_1.setItemText(0, _translate("MainWindow", "?"))
        self.ans11_1.setItemText(1, _translate("MainWindow", "が"))
        self.ans11_1.setItemText(2, _translate("MainWindow", "を"))
        self.label_4.setText(_translate("MainWindow", "2"))
        self.q2.setText(_translate("MainWindow", "イギリス               べんきょうします。"))
        self.ans11_2.setItemText(0, _translate("MainWindow", "?"))
        self.ans11_2.setItemText(1, _translate("MainWindow", "で"))
        self.ans11_2.setItemText(2, _translate("MainWindow", "に"))
        self.label_5.setText(_translate("MainWindow", "3"))
        self.check11_1.setText(_translate("MainWindow", "Check"))
        self.check11_2.setText(_translate("MainWindow", "Check"))
        self.q2_2.setText(_translate("MainWindow", "あの　みせ                食べましょう。"))
        self.ans11_3.setItemText(0, _translate("MainWindow", "?"))
        self.ans11_3.setItemText(1, _translate("MainWindow", "で"))
        self.ans11_3.setItemText(2, _translate("MainWindow", "に"))
        self.check11_3.setText(_translate("MainWindow", "Check"))
        self.label.setText(_translate("MainWindow", "Question 1. Choose the correct word:"))
        self.back_gr11.setText(_translate("MainWindow", "Back"))
        self.label_6.setText(_translate("MainWindow", "4"))
        self.q1_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; color:#717171; background-color:#fffdf7;\">テーブルの うえ           バナナ</span><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; font-weight:400; color:#717171; background-color:#fffdf7;\"/><span style=\" font-family:\'Noto Sans JP\',\'ヒラギノ角ゴ Pro W3\',\'Hiragino Kaku Gothic Pro\',\'メイリオ\',\'Meiryo\',\'ＭＳ Ｐゴシック\',\'sans-serif\'; font-size:20px; color:#717171; background-color:#fffdf7;\">あります。</span></p><p><br/><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; color:#717171;\"/><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; font-weight:400; color:#717171;\"/><a name=\"ui-id-4-button\"/><a href=\"https://a1.marugotoweb.jp/en/grammar_topic6_11.php#nogo\"><span style=\" font-family:\'Verdana\',\'Arial\',\'sans-serif\'; font-size:20px; font-weight:400; color:#666666; background-color:#fffdf7; vertical-align:middle;\"><br/></span></a><span style=\" font-family:\'Noto Sans JP\'; font-size:18px; font-weight:400; color:#717171;\"/><a name=\"ui-id-4-button\"/><a href=\"https://a1.marugotoweb.jp/en/grammar_topic6_11.php#nogo\"><span style=\" font-family:\'Verdana\',\'Arial\',\'sans-serif\'; font-size:20px; font-weight:400; color:#666666; background-color:#fffdf7; vertical-align:middle;\"><br/></span></a></p></body></html>"))
        self.q1_2.setText(_translate("MainWindow", "テーブルの　うえ            バナナ                   あります。"))
        self.ans11_4_1.setItemText(0, _translate("MainWindow", "?"))
        self.ans11_4_1.setItemText(1, _translate("MainWindow", "で"))
        self.ans11_4_1.setItemText(2, _translate("MainWindow", "に"))
        self.ans11_4_2.setItemText(0, _translate("MainWindow", "?"))
        self.ans11_4_2.setItemText(1, _translate("MainWindow", "が"))
        self.ans11_4_2.setItemText(2, _translate("MainWindow", "を"))
        self.label_7.setText(_translate("MainWindow", "5"))
        self.check11_4.setText(_translate("MainWindow", "Check"))
        self.q1_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.q1_3.setText(_translate("MainWindow", "A:                   サッカーを　しますか。                 B: いいえ、                  しません。"))
        self.ans11_5_1.setItemText(0, _translate("MainWindow", "?"))
        self.ans11_5_1.setItemText(1, _translate("MainWindow", "よく"))
        self.ans11_5_1.setItemText(2, _translate("MainWindow", "ぜんぜん"))
        self.check11_5.setText(_translate("MainWindow", "Check"))
        self.ans11_5_2.setItemText(0, _translate("MainWindow", "?"))
        self.ans11_5_2.setItemText(1, _translate("MainWindow", "よく"))
        self.ans11_5_2.setItemText(2, _translate("MainWindow", "あまり"))
        self.label_8.setText(_translate("MainWindow", "6"))
        self.q2_3.setText(_translate("MainWindow", "やすみの　ひに                かいものを　します。"))
        self.ans11_6.setItemText(0, _translate("MainWindow", "?"))
        self.ans11_6.setItemText(1, _translate("MainWindow", "ときどき"))
        self.ans11_6.setItemText(2, _translate("MainWindow", "あまり"))
        self.check11_6.setText(_translate("MainWindow", "Check"))
        self.nextp2_11.setText(_translate("MainWindow", "Next"))
