# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grammar13.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2362, 1043)
        MainWindow.setStyleSheet("background-color: rgb(255, 248, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.w1 = QtWidgets.QWidget(self.centralwidget)
        self.w1.setGeometry(QtCore.QRect(0, 0, 1011, 1091))
        self.w1.setStyleSheet("border-image:url(:/maybay/hinh-nen-iphone-may-bay-cuc-chat-cho-dan-dam-me-xe-dich-12.webp);\n"
"")
        self.w1.setObjectName("w1")
        self.w2 = QtWidgets.QWidget(self.centralwidget)
        self.w2.setGeometry(QtCore.QRect(990, 0, 1920, 1080))
        self.w2.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(113, 110, 221, 255), stop:1 rgba(255, 255, 255, 255));")
        self.w2.setObjectName("w2")
        self.ex13 = QtWidgets.QPushButton(self.w2)
        self.ex13.setGeometry(QtCore.QRect(300, 660, 321, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ex13.setFont(font)
        self.ex13.setStyleSheet("QPushButton {\n"
"    border: 5px solid black;\n"
"    background-color: rgb(170, 255, 255);\n"
"    border-radius: 50px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(0, 255, 255); \n"
"}")
        self.ex13.setFlat(True)
        self.ex13.setObjectName("ex13")
        self.gra13 = QtWidgets.QPushButton(self.w2)
        self.gra13.setEnabled(True)
        self.gra13.setGeometry(QtCore.QRect(300, 340, 321, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gra13.setFont(font)
        self.gra13.setStyleSheet("QPushButton {\n"
"    border: 5px solid black;\n"
"    background-color: rgb(170, 255, 255);\n"
"    border-radius: 50px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(0, 255, 255); \n"
"}\n"
"")
        self.gra13.setAutoDefault(False)
        self.gra13.setDefault(False)
        self.gra13.setFlat(True)
        self.gra13.setObjectName("gra13")
        self.label = QtWidgets.QLabel(self.w2)
        self.label.setGeometry(QtCore.QRect(740, 0, 191, 91))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("image: url(:/logo/62264bc2694c9812c15d.jpg);\n"
"border: 5px solid black;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.back_home13 = QtWidgets.QPushButton(self.w2)
        self.back_home13.setGeometry(QtCore.QRect(40, 920, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.back_home13.setFont(font)
        self.back_home13.setStyleSheet("QPushButton {\n"
"    border: 5px solid black;\n"
"    background-color: rgb(170, 255, 255);\n"
"    border-radius: 25px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(0, 255, 255); \n"
"}")
        self.back_home13.setObjectName("back_home13")
        self.w2.raise_()
        self.w1.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dokugaku"))
        self.ex13.setText(_translate("MainWindow", "EXERCISES"))
        self.gra13.setText(_translate("MainWindow", "GRAMMAR"))
        self.back_home13.setText(_translate("MainWindow", "Back"))
import anhnen_rc
import getthere_rc
import hobby_rc
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
