# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grammar12.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2362, 1043)
        MainWindow.setStyleSheet("background-color: rgb(255, 248, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.w1 = QtWidgets.QWidget(self.centralwidget)
        self.w1.setGeometry(QtCore.QRect(0, 0, 1011, 1091))
        self.w1.setStyleSheet("border-image:url(:/travel/c2833489e13297ed6c472b8241bae81f.jpg)\n"
"")
        self.w1.setObjectName("w1")
        self.w2 = QtWidgets.QWidget(self.centralwidget)
        self.w2.setGeometry(QtCore.QRect(990, 0, 1920, 1080))
        self.w2.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 162, 110, 255), stop:1 rgba(255, 255, 255, 255));")
        self.w2.setObjectName("w2")
        self.ex12 = QtWidgets.QPushButton(self.w2)
        self.ex12.setGeometry(QtCore.QRect(300, 660, 321, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ex12.setFont(font)
        self.ex12.setStyleSheet("QPushButton {\n"
"    border: 5px solid black;\n"
"    background-color: rgb(255, 85, 127);\n"
"    border-radius: 50px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgbrgb(255, 85, 0); \n"
"}")
        self.ex12.setFlat(True)
        self.ex12.setObjectName("ex12")
        self.gra12 = QtWidgets.QPushButton(self.w2)
        self.gra12.setEnabled(True)
        self.gra12.setGeometry(QtCore.QRect(300, 340, 321, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gra12.setFont(font)
        self.gra12.setStyleSheet("QPushButton {\n"
"    border: 5px solid black;\n"
"    background-color: rgb(255, 85, 127);\n"
"    border-radius: 50px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgbrgb(255, 85, 0); \n"
"}\n"
"")
        self.gra12.setAutoDefault(False)
        self.gra12.setDefault(False)
        self.gra12.setFlat(True)
        self.gra12.setObjectName("gra12")
        self.label = QtWidgets.QLabel(self.w2)
        self.label.setGeometry(QtCore.QRect(740, 0, 201, 91))
        self.label.setStyleSheet("image: url(:/logo/62264bc2694c9812c15d.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.back_home12 = QtWidgets.QPushButton(self.w2)
        self.back_home12.setGeometry(QtCore.QRect(40, 920, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.back_home12.setFont(font)
        self.back_home12.setStyleSheet("QPushButton {\n"
"    border: 5px solid black;\n"
"    background-color: rgb(255, 85, 127);\n"
"    border-radius: 25px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgbrgb(255, 85, 0); \n"
"}\n"
"")
        self.back_home12.setObjectName("back_home12")
        self.w2.raise_()
        self.w1.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dokugaku"))
        self.ex12.setText(_translate("MainWindow", "EXERCISES"))
        self.gra12.setText(_translate("MainWindow", "GRAMMAR"))
        self.back_home12.setText(_translate("MainWindow", "Back"))
import anhnen_rc
import hobby_rc
import logo_rc
import travel_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
