# Form implementation generated from reading ui file 'd:\Python\Bai tap\LapTrinhHDT\GUI\home.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1960, 1189)
        MainWindow.setStyleSheet("background-color: rgb(255, 252, 197);")
        self.widget_2 = QtWidgets.QWidget(parent=MainWindow)
        self.widget_2.setObjectName("widget_2")
        self.widget = QtWidgets.QWidget(parent=self.widget_2)
        self.widget.setGeometry(QtCore.QRect(0, 0, 871, 1191))
        self.widget.setStyleSheet("border-image: url(:/grapic/pexels-ena-marinkovic-1814213-3640930.jpg);")
        self.widget.setObjectName("widget")
        self.b_topic11 = QtWidgets.QPushButton(parent=self.widget_2)
        self.b_topic11.setGeometry(QtCore.QRect(1170, 240, 511, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b_topic11.setFont(font)
        self.b_topic11.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(170, 170, 127);\n"
"    border-radius: 30px;\n"
"    padding: 10px;\n"
"    box-shadow: 1px 1px 0px rgba(255, 255, 255, 0.5) inset,\n"
"                1px 1px 0px rgba(0, 0, 0, 0.5) inset,\n"
"                2px 2px 2px rgba(0, 0, 0, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    box-shadow: none;\n"
"    background-color: rgb(170, 170, 0);\n"
"}")
        self.b_topic11.setObjectName("b_topic11")
        self.b_topic12 = QtWidgets.QPushButton(parent=self.widget_2)
        self.b_topic12.setGeometry(QtCore.QRect(1170, 420, 511, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b_topic12.setFont(font)
        self.b_topic12.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(170, 170, 127);\n"
"    border-radius: 30px;\n"
"    padding: 10px;\n"
"    box-shadow: 1px 1px 0px rgba(255, 255, 255, 0.5) inset,\n"
"                1px 1px 0px rgba(0, 0, 0, 0.5) inset,\n"
"                2px 2px 2px rgba(0, 0, 0, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    box-shadow: none;\n"
"    background-color: rgb(170, 170, 0);\n"
"}")
        self.b_topic12.setObjectName("b_topic12")
        self.b_topic13 = QtWidgets.QPushButton(parent=self.widget_2)
        self.b_topic13.setGeometry(QtCore.QRect(1170, 600, 511, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b_topic13.setFont(font)
        self.b_topic13.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(170, 170, 127);\n"
"    border-radius: 30px;\n"
"    padding: 10px;\n"
"    box-shadow: 1px 1px 0px rgba(255, 255, 255, 0.5) inset,\n"
"                1px 1px 0px rgba(0, 0, 0, 0.5) inset,\n"
"                2px 2px 2px rgba(0, 0, 0, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    box-shadow: none;\n"
"    background-color: rgb(170, 170, 0);\n"
"}")
        self.b_topic13.setObjectName("b_topic13")
        self.b_topic14 = QtWidgets.QPushButton(parent=self.widget_2)
        self.b_topic14.setGeometry(QtCore.QRect(1170, 780, 511, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b_topic14.setFont(font)
        self.b_topic14.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(170, 170, 127);\n"
"    border-radius: 30px;\n"
"    padding: 10px;\n"
"    box-shadow: 1px 1px 0px rgba(255, 255, 255, 0.5) inset,\n"
"                1px 1px 0px rgba(0, 0, 0, 0.5) inset,\n"
"                2px 2px 2px rgba(0, 0, 0, 0.5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    box-shadow: none;\n"
"    background-color: rgb(170, 170, 0);\n"
"}")
        self.b_topic14.setObjectName("b_topic14")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setGeometry(QtCore.QRect(1280, 20, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 2px solid black;\n"
"    background-color: rgb(170, 170, 127);\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    box-shadow: 1px 1px 0px rgba(255, 255, 255, 0.5) inset,\n"
"                1px 1px 0px rgba(0, 0, 0, 0.5) inset,\n"
"                2px 2px 2px rgba(0, 0, 0, 0.5);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.widget_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grammar"))
        self.b_topic11.setText(_translate("MainWindow", "Lesson 11: What\'s your hobby?"))
        self.b_topic12.setText(_translate("MainWindow", "Lesson 12: Shall We Go Together?"))
        self.b_topic13.setText(_translate("MainWindow", "Lesson 13: How to get there?"))
        self.b_topic14.setText(_translate("MainWindow", "Lesson 14: It\'s a famous temple"))
        self.label.setText(_translate("MainWindow", "CHOOSE LESSON"))
